### ISSUE TITLE
outrigger with npm link crash

### ISSUE THREAD

**Issue by jadbox** [juttle/outrigger#129]
I'm looking to use outrigger by reference in a project (can't use npm -g in our case) and when trying to use the outrigged linked resource, I get the below error:

* Clone outrigger + `npm install --production && npm link`
* `npm link outrigger'
* Go into another project + `npm link outrigger`
* try to run the daemon:

NPM ver: 2.14.7
```
> reportal-outrigger@1.0.0 outriggerd /home/jdunlap/github/vidroll/reportal-outrigger
> outriggerd --config juttle-config.json -o outriggerd.log

module.js:339
    throw err;
    ^

Error: Cannot find module './source-map/source-map-generator'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/jdunlap/github/vidroll/jut/outrigger/node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map.js:6:30)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/jdunlap/github/vidroll/jut/outrigger/node_modules/webpack/node_modules/webpack-core/lib/Source.js:5:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/jdunlap/github/vidroll/jut/outrigger/node_modules/webpack/node_modules/webpack-core/lib/ReplaceSource.js:5:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

npm ERR! Linux 4.2.0-0.bpo.1-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "outriggerd"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! reportal-outrigger@1.0.0 outriggerd: `outriggerd --config juttle-config.json -o outriggerd.log`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reportal-outrigger@1.0.0 outriggerd script 'outriggerd --config juttle-config.json -o outriggerd.log'.
npm ERR! This is most likely a problem with the reportal-outrigger package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     outriggerd --config juttle-config.json -o outriggerd.log
npm ERR! You can get their info via:
npm ERR!     npm owner ls reportal-outrigger
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jdunlap/github/vidroll/reportal-outrigger/npm-debug.log
```

**Comment by jadbox** [comment]
Perhaps ```npm install --production``` misses a required dependency for Outriggerd?

**Comment by jadbox** [comment]
Sometimes getting this issue with a regular install:
```
npm i           [13:14:31]

> outrigger@0.4.0 prepublish /home/jdunlap/github/vidroll/jut/outrigger
> npm run clean && npm run build-client


> outrigger@0.4.0 clean /home/jdunlap/github/vidroll/jut/outrigger
> rimraf dist


> outrigger@0.4.0 build-client /home/jdunlap/github/vidroll/jut/outrigger
> webpack

Hash: 10f487b85e20c9e64cd2
Version: webpack 1.12.12
Time: 35ms
    + 1 hidden modules

ERROR in Cannot find module 'lodash/lang/isFunction'
```

**Comment by dmehra** [comment]
I don't know if this is necessarily related, but npm version 2.4.17 is a bit old. This is what I run (without the issues you observed); fwiw my environment is with `nvm`:
```
$ npm --version
3.5.2
$ node --version
v4.2.4
```

**Comment by go-oleg** [comment]
I confirmed locally that doing a git clone followed by `npm install --production` doesn't work because this neither downloads the compiled assets in `dist` (which are built on prepublish and not available on github) and nor the `devDependencies` that are necessary to run outrigger when `dist` isn't present.

**Comment by go-oleg** [comment]
To followup, the convention is that cloning/running from github is used for dev purposes/running outrigger in dev mode whereas installing from npm is used for production purposes. Does that gel with your expectations?

**Comment by jadbox** [comment]
I think so: worked around the issue using NPM instead of using the GH source
