### ISSUE TITLE
outriggerd fails to start due to non-existent log file

### ISSUE THREAD

**Issue by philrz** [juttle/outrigger#137]
Running a fresh install on Ubuntu Linux, following the steps in the Outrigger README. It fails at this step:

```
# outriggerd -d -o outriggerd.log
fs.js:203
  binding.access(pathModule._makeLong(path), mode);
          ^

Error: ENOENT: no such file or directory, access 'outriggerd.log'
    at Error (native)
    at Object.fs.accessSync (fs.js:203:11)
    at Object.module.exports.init (/usr/local/lib/node_modules/outrigger/bin/log-setup.js:32:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/outrigger/bin/outriggerd:67:10)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

If I "touch outriggerd.log" and repeat, it starts fine. So, the workaround is easy. But I was expecting it to make the empty file automatically rather than bomb out.

**Comment by mstemm** [comment]
This should be fixed as a part of https://github.com/juttle/juttle-service/pull/40. I tested using a recent juttle-engine and it did create the log file:

`$ bin/juttle-engine -d -o log.txt
$ cat log.txt
[2016-02-23 10:30:54.289] [INFO] juttle-engine - Juttle engine listening at http://0.0.0.0:8080 with root directory: /`

Feel free to reopen under juttle-engine if you're still having problems.
